# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 11cc9b384ce9fe733279e7debd06043a90051bc73ae2028a4193791579ef193499c6e1341c0e1b257eea753dff2aa8ed343433d79c0f656c4e357670f4e3ff55

test:
  secret_key_base: 3a56752ec2bfe3bbad26ca0c22357d903962641b1af890ea15d78cd5a39534dd6f8fd21933ff689872f40327b11ff2d9647819e8c7301c78a0c3a5ffa5939ac9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
